[[questions]]
type = "ShortAnswer"
prompt.prompt = "Have you previously taken any OS lecture or did you go through any OS resources?"
answer.answer = "let"
context = "For example, you can write: `Yes`"
id = "cs000"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "What does it mean if a variable `x` is immutable?"
prompt.distractors = [
  "`x` is stored in the immutable region of memory.",
  "After being defined, `x` can be changed at most once.",
  "You cannot create a reference to `x`."
]
answer.answer = "`x` cannot be changed after being assigned to a value."
context = """
Immutable means "not mutable", or not changeable.
"""
id = "cs001"
